export const turkishStrings = {
  main: {
    no: "Hayır",
    yes: "Evet",
    ok: "Tamam",
    edit: "Düzenle",
    save: "Kaydet",
    add: "Ekle",
    cancel: "İptal",
    warning: "Uyarı",
    select: "Seç",
    customer: "Müşteri",
    recipe: "Reçete",
    retry: "Tekrar Dene",
    error: "Hata",
    loading: "Yükleniyor",
    totalWeight: "Toplam Ağırlık",
    close: "Kapat",
    approve: "Onayla",
    status: "Durum",
  },
  menu: {
    home: "Ana Sayfa",
    productionPlans: "İmalat Planları",
    recipeList: "Reçeteler",
    factoryManagement: "Fabrika Yönetimi",
    techSupport: "Teknik Destek",
    allRecipes: "Tüm Reçeteler",
    activeRecipes: "Aktif Reçeteler",
    activePlans: "Sıradaki Planlar",
    planList: "Planlar",
    orders: "Siparişler",
    onHold: "Beklemede",
    approvedOrders: "Onaylanmış",
    nonApprovedOrders: "Onaylanmamış",
  },
  plans: {
    headerBatch: "Parti",
    headerRecipeName: "Reçete",
    headerBatchCount: "Batch",
    multiplier: "Çarpan",
    batchCount: "Batch Adedi",
    addNewPlan: "Yeni Plan Ekle",
    onDeletePlan: "Bu planı silmek istediğinize emin misiniz?",
    activeBatch: "Son Batch",
    inProd: "Üretimde",
  },
  errors: {
    somethingHappened: "Bir hata oluştu",
  },
  recipes: {
    active: "Aktif",
    inactive: "Pasif",
    recipeNotFound: "Reçete bulunamadı",
    showDetails: "Detayları Göster",
    recipeDetails: "Reçete Detayları",
    totalWeight: "Toplam Ağırlık",
    revisionNo: "Revizyon No",
    ingredients: "İçerikler",
    additionalInfo: "Ek Bilgiler",
    fatCoating: "Yağ Kaplama",
    molasses: "Melas",
    vinasse: "Vinas",
    additive: "Katkı",
  },
  orders: {
    shipmentDate: "Sevkiyat Tarihi",
    remaining: "Kalan Süre",
    amount: "Miktar",
    approved: "Onaylandı",
    canceled: "İptal edildi",
    onHold: "Onay Bekliyor",
    addNewOrder: "Yeni Sipariş Ekle",
    putOnHold: "Beklet",
  },
};
